name: Prebuild docker image
on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    name: BUILD
    runs-on: ubuntu-22.04
    timeout-minutes: 600
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry (GHCR)
        if: github.event_name != 'pull_request' && github.repository == 'antmicro/openroad-codespace'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: gha
          password: ${{ github.token }}

      - name: Build ORFS
        run: |
          docker build -t ghcr.io/antmicro/openroad-codespace:orfs -f Dockerfile-orfs .

      - name: Push container image to GitHub Container Registry (GHCR)
        if: github.event_name != 'pull_request' && github.repository == 'antmicro/openroad-codespace'
        run: docker push ghcr.io/antmicro/openroad-codespace:orfs

      - name: Build LXQt
        run: |
          docker build -t ghcr.io/antmicro/openroad-codespace:lxqt -f Dockerfile-lxqt .

      - name: Push container image to GitHub Container Registry (GHCR)
        if: github.event_name != 'pull_request' && github.repository == 'antmicro/openroad-codespace'
        run: docker push ghcr.io/antmicro/openroad-codespace:lxqt
