name: Build OpenROAD Docker

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
      - cron: '0 */24 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build-docker:
    env:
        REPOSITORY_NAME: openroad-codespace
    runs-on: ubuntu-latest
    steps:
      - name: Cache
        uses: actions/cache@v4
        with:
          path: "~/.cache/"
          key: cache-${{ github.sha }}
          restore-keys: cache-

      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build container image
        run: |
          cd third_party/OpenROAD-flow-scripts/
          ./etc/DockerHelper.sh create -os=ubuntu22.04 -target=builder
          cd -
          docker image tag openroad:flow-ubuntu22.04-builder:latest openroad-codespace:latest

      - name: Login to GitHub Container Registry (GHCR)
        if: github.event_name != 'pull_request' && github.repository == 'antmicro/openroad-codespace'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: gha
          password: ${{ github.token }}

      - name: Push container image to GitHub Container Registry (GHCR)
        if: github.event_name != 'pull_request' && github.repository == 'antmicro/openroad-codespace'
        run: docker push openroad/ubuntu22.04-builder:latest
